services:
  - type: web
    name: polling-app
    env: node
    rootDir: server
    buildCommand: |
      cd ../client && npm install && npm run build
      cd ../server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
